### ISSUE TITLE
Building for Linux error missing CmakeList.txt in mbdx

### ISSUE THREAD

**Issue by devisbal** [basiliscos/syncspirit#4]
Hi,

I have tried to buikd for linux, static and shared but:

CMake Error at CMakeLists.txt:181 (add_subdirectory):
  The source directory
    /root/syncspirit/lib/mbdx
  does not contain a CMakeLists.txt file.

CMake Warning at src/ui-daemon/CMakeLists.txt:55 (message):
  upx not found

BR

**Comment by basiliscos** [comment]
```
git clone --recurse-submodules https://github.com/basiliscos/syncspirit
```

should do the thing :)
